### ISSUE TITLE
Does ember-cli-bootstrap-datepicker work with the npm version of bootstrap-datepicker ?

### ISSUE THREAD

**Issue by ieugen** [soulim/ember-cli-bootstrap-datepicker#103]
Hello,

We are in the process of removing `bower` from our ember app since bower is well, going out the door. 
Since we are using ember-cli-bootstrap-datepicker we tryed using the npm version of bootstrap-datepicker but that does not seem to work in our build. 

p.s. I'm quite new to the node build ecosystem and I might be doing something wrong. 

If it does not work however, please try to address this issue as I believe we should simplify things, build process included :). 

Thanks,

Running `ember serve`
````
Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory, open '/gr8pi/gr8pi-ui-client/tmp/source_map_concat-input_base_path-wNyWYwLx.tmp/vendor/ember/ember.debug.map'
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, open '/gr8pi/gr8pi-ui-client/tmp/source_map_concat-input_base_path-wNyWYwLx.tmp/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at SourceMap.addFile (/gr8pi/gr8pi-ui-client/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /gr8pi/gr8pi-ui-client/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/gr8pi/gr8pi-ui-client/node_modules/broccoli-concat/concat.js:198:24)
    at /gr8pi/gr8pi-ui-client/node_modules/fast-sourcemap-concat/lib/source-map.js:399:12
    at initializePromise (/gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:1039:33)
    at SourceMap.end (/gr8pi/gr8pi-ui-client/node_modules/fast-sourcemap-concat/lib/source-map.js:386:10)
    at Concat._doLegacyBuild (/gr8pi/gr8pi-ui-client/node_modules/broccoli-concat/concat.js:183:22)
    at Concat.build (/gr8pi/gr8pi-ui-client/node_modules/broccoli-concat/concat.js:106:17)
    at /gr8pi/gr8pi-ui-client/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:2415:5)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)


The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/gr8pi/gr8pi-ui-client/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at EmberApp._mergeTrees (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/lib/broccoli/ember-app.js:1815:12)
    at EmberApp.javascript (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/lib/broccoli/ember-app.js:1297:17)
    at EmberApp.toArray (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/lib/broccoli/ember-app.js:1672:12)
    at EmberApp.toTree (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/lib/broccoli/ember-app.js:1694:38)
    at module.exports (/gr8pi/gr8pi-ui-client/ember-cli-build.js:92:14)
    at Builder.setupBroccoliBuilder (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/gr8pi/gr8pi-ui-client/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at /gr8pi/gr8pi-ui-client/node_modules/ember-cli/lib/models/command.js:243:46
    at tryCatch (/gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:538:13)
    at /gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/gr8pi/gr8pi-ui-client/node_modules/rsvp/dist/rsvp.js:2415:5)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)

````

**Comment by ieugen** [comment]
This article explains how to load from npm in the addon https://simplabs.com/blog/2017/02/13/npm-libs-in-ember-cli.html

**Comment by MoxyFruzy** [comment]
There's a PR for this #96
